name: check2

on:
  pull_request:
    types: [ synchronize, opened, reopened ]
    branches:
      - gh-pages1
  push:
    branches: [ main ]
jobs:
  run_check:
    name: Start run_check
    runs-on: ubuntu-latest
    steps:
    - name: Run dummy test
      run: |
        echo "Running check..."
        exit 0 
