name: check2

on:
  release:
    types: [released]
jobs:
  run_check:
    name: Start run_check
    runs-on: ubuntu-latest
    steps:
    - name: Run dummy test
      run: |
        echo "Running check..."
        exit 1
