name: check2

on:
  pull_request:
    types: [ synchronize, opened, reopened ]
    branches:
      - gh-pages
  push:
    branches: [ main ]
jobs:
  run_check:
    uses: myTestOrg0/tf-github-workflows/.github/workflows/tf-validate.yaml@main
    with:
      working-directory: . 
