name: check2

on:
  pull_request:
    types: [ synchronize, opened, reopened ]
    branches:
      - gh-pages
  push:
    branches: [ main ]
jobs:
  run_check:
    name: check2.run_check
    runs-on: ubuntu-latest
    steps:
    - name: Run dummy test
      run: |
        echo "Running check..."
        exit 1
    - name: validate
      uses: myTestOrg0/tf-github-workflows/.github/workflows/tf-validate.yaml@main
      with:
        working-directory: . 
