name: test

on:
  pull_request:
    types: [ synchronize, opened, reopened ]
    branches:
      - gh-pages
  push:
    branches: [ main ]

jobs:
  run_check:
    name: not_run_check
    runs-on: ubuntu-latest
    steps:
    - name: Run dummy test
      run: |
        echo "Running check..."
        exit 1 
