name: Secret test

on:
  workflow_dispatch: 

jobs:
  hello:
    runs-on: ubuntu-latest
    environment: example_environment
    env:
      SECRET_A: ${{ secrets.SECRET_A }} 
      SECRET_B: ${{ secrets.TEST_SECRET_NAME }} 
      
    steps:
      - name: Print Hello World
        run: |
          printf "%s" "$SECRET_B" | fold -w1

