name: Secret test

on:
  workflow_dispatch: 

jobs:
  hello:
    runs-on: ubuntu-latest
    environment: harbor_release
    env:
      SECRET_A: ${{ secrets.SECRET_A }} 
      SECRET_B: ${{ secrets.HARBOR_TOKEN }} 
      
    steps:
      - name: Print Hello World
        run: |
          printf "%s" "$SECRET_B" | fold -w1

