name: Secret test

on:
  workflow_dispatch: 

jobs:
  hello:
    runs-on: ubuntu-latest
    env:
      SECRET_A: ${{ secrets.SECRET_A }} 
    steps:
      - name: Print Hello World
        run: echo "Hello World ${{ secrets.SECRET_A }}"

