name: Secret test

on:
  workflow_dispatch: 

jobs:
  hello:
    runs-on: ubuntu-latest
    env:
      SECRET_A: ${{ secrets.SECRET_A }} 
      SECRET_B: ${{ secrets.SECRET_B }} 
      
    steps:
      - name: Print Hello World
        run: ${{ secrets.SECRET_A }}

