name: test

on:
  pull_request:
    types: [ synchronize, opened, reopened ]
    branches:
      - main
permissions:
  contents: write
  security-events: write

env:
  NODE_OPTIONS: --max_old_space_size=4096

jobs:
